version: '3.8'

services:
  ecc-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecc-web-prototype
    ports:
      - "4003:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production